name: fixngo_technician
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  geolocator: ^14.0.3
  image_picker: ^1.1.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  mqtt_client: ^10.4.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/images/logo4.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo4.png"
  web:
    generate: true
    image_path: "assets/images/logo4.png"
    background_color: "transparent"
  image_path: "assets/images/logo4.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/